version: '3.6'

services:
  postgres:
    container_name: 'scandir_postgres'
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5555:5555
    expose:
      - 5555/tcp
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    command: -p 5555
    volumes:
      - ./database/data:/var/lib/postgresql/data # persist data
      - ./database/backups:/usr/src/backups # store backups
